---
title: "Radiative transfer model plots"
author: Simone Massaro
date: 11/01/21
output: html_notebook
---
# Load the model and setup

```{r}
library(readxl)
library(tidyverse)
```
```{r}
source("radiative_transfer_model.R")
```

parameters for Hainich (use as default parameters for model)
```{r}
source('parameters_hainich.R')
p <-  params
```

## LAI over the year

```{r}
days <- seq.Date(as.Date("2020-01-01"), as.Date("2020-12-31"), by=1)
LAIs <- Vectorize(get_day_LAI, "datetime")(days,  p$max_LAI, p$min_LAI, p$leaf_out, p$leaf_full, p$leaf_fall, p$leaf_fall_complete)

ggplot() + geom_line(aes(x=days, y=LAIs))
```
This is not that intersting is just a linear value
```{r}
fake_input <- tibble(
    datetime = as.Date("2020-07-15 12:00"), # Summer day
    sw_sky_b = 100:800,
    sw_sky_d = 100,
    lw_sky = 200,
    t_soil = 300,
    t_leaf = 300
)

out_1 <- radiative_transfer_over_input(fake_input, p)

ggplot() +
  geom_line(aes(x=fake_input$sw_sky_b, y=out_1$ic)) +
  geom_line(aes(x=fake_input$sw_sky_b, y=out_1$ic_sun)) +
  geom_line(aes(x=fake_input$sw_sky_b, y=out_1$ic_sha))
```

Absorbed radiation vs LAI
```{r}
# The same code just LAI is an input is not calculated
radiative_transfer_model_step_custom_LAI <- function(input, p){

    zenith <- get_zenith(input$datetime, p$lat, p$lon) # should be 15 mins earlier because is a better average value of the half an hour interval
    Kb <- get_Kb(zenith)
    Kd <- get_Kd(input$LAI)
    beta <- get_beta(p$rho_leaf, p$tau_leaf)
    beta0 <- get_beta0(zenith, Kb, Kd, p$omega_leaf)

    shortwave <- shortwave_radiation(input$sw_sky_b, input$sw_sky_d, input$LAI, Kd, Kd, beta, beta0 , p$omega_leaf,
                                     p$clump_OMEGA, p$alb_soil_b, p$alb_soil_d)
    longwave <- longwave_radiation(input$lw_sky, input$LAI, input$t_leaf, input$t_soil, Kb, Kd, p$em_leaf, p$em_soil)

    # values calculated during model run outputed to give more info about the model
    interm_params <- list(LAI=input$LAI, Kb=Kb, Kd=Kd, beta=beta, beta0 = beta0)

    return(data.frame(c(shortwave, longwave, interm_params)))

}

radiative_transfer_over_input_custom_LAI <- function (input, params) {

  # Initiate an empty dataframe to hold output
  len <- nrow(input)
  out <- tibble(
        # shortwave
        ic = double(len),       # total absorbed shortwave
        ic_sun = double(len),   # absorbed shortwave from sunlit leaves
        ic_sha = double(len),   # absorbed shortwave from shaded leaves
        ig = double(len),       # shortwave absorbed by the soil
        i_up = double(len),     # shortwave emitted above the canopy
        i_down = double(len),   # shortwave reaching the soil

        #longwave
        lc = double(len),       # total absorbed longwave from canopy
        lg = double(len),       # total absorbed longwave from soil
        lc_sun = double(len),   # absorbed longwave from sunlit leaves
        lc_sha = double(len),   # absorbed longwave from shaded leaves
        l_up = double(len),     # emitted longwave above the canopy
        l_down = double(len),    # longwave reaching the soil

        # additional parameters
        LAI = double(len),
        Kb = double(len),
        kd = double(len),
        beta = double(len),
        beta0 = double(len)
  )

  print("Running radiative transfer model")
  pb <- txtProgressBar(1, max(len, 2)) # quick hack if there is only 1 line in input
  for (i in seq_len(nrow(input))){
    out_step <- radiative_transfer_model_step_custom_LAI(input[i,], params)
    out[i,] <-  out_step

    setTxtProgressBar(pb, i)
  }

  return(out)
}
fake_input_2 <- tibble(
    datetime = as.Date("2020-07-15 12:00"), # Summer day
    sw_sky_b = 800,
    sw_sky_d = 100,
    lw_sky = 200,
    t_soil = 300,
    t_leaf = 300,
    LAI = 1:10
)
out_2 <- radiative_transfer_over_input_custom_LAI(fake_input_2, p)
```
```{r}
ggplot() +
  geom_line(aes(x=fake_input_2$LAI, y=out_2$ic)) +
  geom_line(aes(x=fake_input_2$LAI, y=out_2$ic_sun)) +
  geom_line(aes(x=fake_input_2$LAI, y=out_2$ic_sha))
```

# Test with real data

## Load data

```{r}
read_fluxnet_data <- function(path) {
  read_excel(path, na = "-9999") %>%
    select("Date/Time", SW_IN_F, SW_DIF, SW_OUT, LW_IN_F, LW_OUT, TS_F_MDS_1, TA_F) %>% # Columns interesting for radiative model
    rename(datetime = "Date/Time") %>%
    transmute(datetime = datetime,
              sw_sky_d = SW_DIF,
              sw_sky_b = SW_IN_F - sw_sky_d,  # SW_IN_F is the total radiation direct + diffuse
              lw_sky = LW_IN_F,
              t_leaf = 273.15 + TA_F,       # Temperature of air aproximation for leaf T for now
              t_soil = 273.15 + TS_F_MDS_1, # Temp soil at 2cm depth
              sw_out = SW_OUT,
              lw_out = LW_OUT

    )
}
```
```{r}
flux_data_path <- "../data/FLX_DE-Hai_FLUXNET2015_FULLSET_HH_2016-2018_beta-3_for_class.xlsx"
flux <-  read_fluxnet_data(flux_data_path)
```
Loads into params the parameters of the site
```{r}
source('parameters_hainich.R')
```

Taking the first year of flux data
```{r}
t_data <- flux[flux$datetime < as.Date("2017-01-01"), ]
```

## Running the model
```{r}
out <- radiative_transfer_over_input(t_data, p)
```

```{r}
ggplot() + geom_point(aes(x=out$i_up, y=t_data$sw_out)) + geom_abline(intercept = 0, slope = 1, color="red")
```
```{r}
out %>% cbind(t_data) %>% # add the index
        gather("Radiation_type", "Absorbed_radiation", c("ic", "ic_sun", "ic_sha")) %>%
        ggplot() +
        geom_line(aes(x=datetime, y=Absorbed_radiation, color=Radiation_type))
```
```{r}
out %>% cbind(t_data) %>% # add the index
        select(datetime, i_up, sw_out)
        gather("Model/Real data", "Emitted_radiation", c("ic", "ic_sun", "ic_sha")) %>%
        ggplot() +
        geom_line(aes(x=datetime, y=Absorbed_radiation, color="Model/Real data"))
```
